name: Metrics
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
     contents: write
    steps:
      - name: Metrics 1
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics.svg
          user: sisuolv
          base: header, repositories,activity, community, metadata
          config_timezone: Asia/Hong_Kong

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_lines: yes
